### ISSUE TITLE
Idea: Safe Base91

### ISSUE THREAD

**Issue by DonaldTsang** [kstenerud/safe-encoding#1]
http://base91.sourceforge.net/
- A version where it is SGML and JSON safe
- A version where it is URI safe

**Comment by kstenerud** [comment]
I thought about larger alphabets, but unfortunately, there are only 94 printable characters. base91 would mean that one could only drop 3 characters, which means that it could not be SGML safe (SGML has 4 characters that are reserved in all contexts).

https://github.com/kstenerud/safe-encoding/blob/master/safe85-specification.md#choice-of-alphabet
