### ISSUE TITLE
Safe85 values 36 and 52 are the same

### ISSUE THREAD

**Issue by berezovskyi** [kstenerud/safe-encoding#10]
Both are 0x60 in ASCII in the spec. Refimpl uses `|` for value 52.

**Comment by kstenerud** [comment]
It looks like the table renderer code in Github doesn't like the pipe for 0x52. The text document is correct, but the renderer is broken.

I'll have to see if there's a workaround.

**Comment by berezovskyi** [comment]
I see, thanks! https://stackoverflow.com/questions/17319940/how-to-escape-a-pipe-char-in-a-code-statement-in-a-markdown-table suggests to use `code `HTML tag.

**Comment by kstenerud** [comment]
A perfect! updated.
