### ISSUE TITLE
Examples provided in safe80 specification are not safe for Windows filenames

### ISSUE THREAD

**Issue by Hakkin** [kstenerud/safe-encoding#7]
2 of the 3 examples provided in the safe80 spec are not safe for Windows filenames.
```
Data:    {0x39, 0x12, 0x82, 0xe1, 0x81, 0x39, 0xd9, 0x8b, 0x39, 0x4c, 0x63, 0x9d, 0x04, 0x8c}
Encoded: +2:uccGG`OPiWR*Ykf

Data:    {0xe6, 0x12, 0xa6, 0x9f, 0xf8, 0x38, 0x6d, 0x7b, 0x01, 0x99, 0x3e, 0x6c, 0x53, 0x7b, 0x60})
Encoded: lB0QXY>FLOPMTk-G=W!

Data:    {0x21, 0xd1, 0x7d, 0x3f, 0x21, 0xc1, 0x88, 0x99, 0x71, 0x45, 0x96, 0xad, 0xcc, 0x96, 0x79, 0xd8})
Encoded: 0eihg),E0D]SaSfOxxB(b
```

The first example contains `:` and `*`.
The second example contains `>`.

**Comment by kstenerud** [comment]
Oh  wow... The safe80 source code has the wrong definition tables! A transcription error somewhere... Those characters aren't even in the safe80 alphabet :P

The spec is correct, but the examples and reference implementation are wrong. Thanks for finding this!

**Comment by kstenerud** [comment]
Fixed here: https://github.com/kstenerud/safe-encoding/commit/79f19c6d0bc04160dea0771ccddae897c59e5cb6
